# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'libPusher', '~> 1.5'
pod "PusherSwift"

target 'Blastermind' do

end

target 'BlastermindTests' do

end

